Task_1_1_1
NikitaTrTr/OOP pull request #1
Opened 2022-09-13 14:31 UTC by NikitaTrTr

2022-09-15 07:01 UTC, Leidenn2509 requested changes
- Удалите папку `.idea` в корне репозитория
- Добавьте `workflow`
- Используйте `.gitignore` вида intellij+all, чтобы не добавлять содержимое папки `.idea` в репозиторийИспользуйте `.gitignore` вида intellij+all, чтобы не добавлять содержимое папки `.idea` в репозиторий
- Добавьте скрипт сборки
- Добавьте тесты
- Добавьте `javadoc`

2022-09-15 07:01 UTC, alradish commented on Task_1_1_1/src/main/java/ru/nsu/ntatarinov/Heapsort.java
> +    public static void siftUp(int n, int[] heap){
Если метод не используется извне класса, стоит сделать его приватным

2022-09-15 07:01 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/ntatarinov/Heapsort.java
> +    public static void main(String[] args){
`main` метод нужно вынести из этого класса, т.к. это не относится к зоне отвественности класса `Heapsort`. Он занимается только сортировкой, а метод `main` это уже общение с пользователем.

2022-09-15 07:01 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/ntatarinov/Heapsort.java
> +        int[]heap = new int[10];
Heapsort должен работать без выделение дополнительной памяти

2022-09-18 09:43 UTC, NikitaTrTr commented
@Leidenn2509, призываю вас

2022-09-18 09:49 UTC, Leidenn2509 approved these changes

2022-09-18 09:49 UTC, merged