Task_2_3_1
NikitaTrTr/OOP pull request #10
Opened 2023-05-18 12:22 UTC by NikitaTrTr

2023-05-18 12:23 UTC, NikitaTrTr commented
Пока чисто код, без тестов, без стиля. Неплохо было бы, чтобы вы еще до вторника дали комментарии именно по коду.

2023-06-14 12:30 UTC, alradish requested changes
Надо отделить javafx от модели. Подробнее пока не смотрел

2023-06-20 17:40 UTC, NikitaTrTr commented
Запись геймплея отправил по почте

2023-06-21 15:37 UTC, alradish requested changes
- [ ] Отображать счёт и сколько осталось до победы
- [ ] Отделение модели от javafx. 

По-хорошему надо вынести модель в отдельный пакет, тогда это будет легче отследить. На данный момент у вас javafx просачивается в модель через SnakeGameView

2023-06-21 15:53 UTC, NikitaTrTr commented
> * [ ]  Отображать счёт и сколько осталось до победы
> 
>     * [ ]  Отделение модели от javafx.
> 
> 
> На данный момент у вас javafx просачивается в модель через SnakeGameView
А каким образом?

2023-06-21 15:54 UTC, NikitaTrTr commented
Модель всего лишь отправляет view текущее состояние игры, а далее view уже раскидывает это внутри себя по методам. Если это неправильный подход, то как иначе выстроить коммуникацию между моделью и view?

2023-06-22 02:02 UTC, alradish approved these changes
Можно как у вас сейчас (пассивная модель), можно было накрутить интерфейсов лисенеров и тогда модель смогла бы уведомлять когда изменила состояние (что-то по типу активной)

2023-06-22 02:02 UTC, merged