Task_1_2_1
NikitaTrTr/OOP pull request #2
Opened 2022-09-23 13:52 UTC by NikitaTrTr

2022-09-26 09:10 UTC, Leidenn2509 requested changes

2022-09-26 09:10 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/ntatarinov/Stack.java
> +    public void push(T elem) {
`element` не экономьте на символах

2022-09-26 09:10 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/ntatarinov/Stack.java
> +    public void push(T elem) {
Нужна проверка на `null`

2022-09-26 09:10 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/ntatarinov/Stack.java
> +        return this.stack[--curSize];
А что если `curSize == 0`

2022-09-26 09:14 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/ntatarinov/Stack.java
> +        this.stack = (T[]) new Object[capacity];
У вас тут ещё ворнинг должен быть. От него надо избавиться

2022-09-26 09:17 UTC, Leidenn2509 commented on Task_1_2_1/src/main/java/ru/nsu/ntatarinov/Stack.java
> +    public T pop() {
Добавьте уменьшение размера массива

2022-09-30 08:30 UTC, Leidenn2509 approved these changes

2022-09-30 08:43 UTC, merged

2022-09-30 09:21 UTC, Leidenn2509 commented
Не резолвите и не мёржите сами

2022-09-30 10:25 UTC, NikitaTrTr commented
Ой ой простите извините. Увидел апрув - решил, что можно мержить. А скажите, почему вы сразу не замержили после апрува? Или апрув реквеста != лаба принята, можно мержить в мастер?

2022-09-30 12:17 UTC, NikitaTrTr commented
@Leidenn2509