Task_1_3_1
NikitaTrTr/OOP pull request #4
Opened 2022-11-20 15:48 UTC by NikitaTrTr

2022-11-21 11:31 UTC, alradish requested changes

2022-11-21 11:31 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/ntatarinov/SubstringFinder.java
> +        return findEntries(zfunc, input, pattern.toCharArray());
Используйте try-with-resources
```Java
try(InputStream input = new FileInputStream(fileName)) {
    Integer[] zfunc = findZfuncForPattern(pattern.toCharArray());
    return findEntries(zfunc, input, pattern.toCharArray());
} catch (...) {...}
```

2022-11-21 11:31 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/ntatarinov/SubstringFinder.java
> +            System.out.println(e.getMessage());
Если вы сами не можете обработать эксепшн, то лучше бросить его выше. Печатать ли его в консоль решит, кто-то выше

2022-11-21 11:31 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/ntatarinov/SubstringFinder.java
> +    private static Integer[] findZfuncForPattern(char[] pattern) {
Можно возвращать просто int[]

2022-11-21 11:31 UTC, alradish commented on Task_1_3_1/src/main/java/ru/nsu/ntatarinov/SubstringFinder.java
> +            index += 1;
Дублирование кода. Надо обобщить поиск з функции

2022-11-29 17:07 UTC, NikitaTrTr commented
Почему то не запустились проверки. Непонятно

2022-11-29 17:09 UTC, NikitaTrTr commented
Во. Сделал еще один пуш и пошло. Странно

2022-12-12 02:08 UTC, alradish approved these changes
В следующих лабах не резолвьте треды сами. Обычно качество исправления оценивает тот, кто его запросил.
+ конкретно здесь мне удобнее отслеживать, что я просил и куда надо посмотреть при повторной проверке

2022-12-12 02:08 UTC, merged