Task_1_5_1
NikitaTrTr/OOP pull request #6
Opened 2022-12-07 13:00 UTC by NikitaTrTr

2022-12-19 03:04 UTC, alradish requested changes

2022-12-19 03:04 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/ntatarinov/Calculator.java
> +        Arrays.asList("+", "-", "*", "/", "log", "pow", "cos", "sin", "sqrt"));
Плохо. Руинит весь смысл фабрики (то, что только фабрика знает об операциях)

2022-12-19 03:04 UTC, alradish commented on Task_1_5_1/src/main/java/ru/nsu/ntatarinov/Calculator.java
> +            if (!ops.contains(token)) {
Можно просто делать getFunc и если null то пушить на стэк

2022-12-21 03:57 UTC, NikitaTrTr commented on Task_1_5_1/src/main/java/ru/nsu/ntatarinov/Calculator.java
> +            if (!ops.contains(token)) {
Хорошая идея. Спасибо за замечание, поправил

2022-12-23 07:52 UTC, alradish requested changes
- Фикс ок, но будет лучше если вы сохраните значение `getFunc`, что бы не звать её два раза
- А что с ревьюдогом, надо исправить

2022-12-25 10:23 UTC, alradish approved these changes

2022-12-25 10:23 UTC, merged